# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:12345/hook/simple
Content-Type: application/json

{
  "URL": "https://github.com/Oppodelldog/simple-ci.git",
  "REV": "ba99de688acc32fb4c0778b9b5b74e8ab9a881eb"
}

###

GET http://localhost:12345/queue
Accept: application/json

###

GET http://localhost:12345/queue/abort/a44b531011324be3867c6c6de47e7685
Accept: application/json

###
# list all build numbers

GET http://localhost:12345/build
Accept: application/json

###
# list all build numbers for a repository

GET http://localhost:12345/build/https___github.com_Oppodelldog_simple-ci.git
Accept: application/json

###
# get the log for one build

GET http://localhost:12345/build/https___github.com_Oppodelldog_simple-ci.git/3
Accept: application/json

###