# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET https://localhost:10443/healthcheck

###
# trigger build by simple hook

POST https://localhost:10443/hook/simple
Content-Type: application/json

{
  "URL": "https://github.com/Oppodelldog/docker-dns.git",
  "REV": "8a7f4f2febb2e5721a608216f6c396b956abcc53"
}

###

GET https://localhost:10443/queue
Accept: application/json

###
# abort running build

POST https://localhost:10443/queue/abort/240dae94991740328df0e58555f04e45
Accept: application/json

###
# list all build numbers

GET https://localhost:10443/build
Accept: application/json

###
# list all build numbers for a repository

GET https://localhost:10443/build/https___github.com_Oppodelldog_plain-ci.git
Accept: application/json

###
# get the log for one build

GET https://localhost:10443/build/https___github.com_Oppodelldog_plain-ci.git/1
Accept: application/json

###